### ISSUE TITLE
Investigate priority queue for slots

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/codex-research#163]
The [sales module](https://github.com/codex-storage/codex-research/blob/master/design/sales.md) is responsible for selling storage by trying to [fill slots in storage requests](https://github.com/codex-storage/codex-research/blob/master/design/marketplace.md#slots). The sales module now reacts to any storage request that matches availability and profit requirements. We should probably design for the sales module to have a priority queue of slots. When a new request comes in, then all its slots are added to the priority queue. And when a slot is in need of repair, it should also be added to the queue. This queue can then be sorted based on the profitability and risk associated with it. This can be calculated from slot properties such as timeout, dataset size, reward, collateral etc.

**Comment by AuHau** [comment]
This was implemented at https://github.com/codex-storage/nim-codex/pull/455
